### ISSUE TITLE
Einrichtung der Kategorien und Öffnung der Registrierung

### ISSUE THREAD

**Issue by acka47** [hbz/metadaten.community#1]
Am Montag findet die nächste [KIM-Sitzung](https://wiki.dnb.de/display/DINIAGKIM/2022-11-28+Sitzung+der+DINI+AG+KIM) statt, zu der wir das Forum eigentlich spätestens öffnen wollten. Wegen Krankheitausfällen ist unklar, ob der Plan zu halten ist.

Frage: Sind erstmal die nötigsten Dinge (Datenschutz, Impressum, Einrichtung der Registrierung) erledigt, um das Forum zu öffnen? Oder müssen wir das verschieben?

Wenn wir es freischalten können, dann schlage ich folgendes Vorgehen vor:

- [x] Wir setzen die bisher erarbeitete Kategorienstruktur  (Meta, Allgemeines, Tools mit Unterkategorien, Arbeitsgruppen mit Unterkategorien) auch in der Produktivinstanz um.
- [ ] Wir beginnen einen Meta-Thread mit dem Titel "Metadatenpraktiker:innen im DACH-Raum" oder ähnlich,  machen das zum Wiki und ergänzen die bisher von uns intern ([hier](https://dienst-wiki.hbz-nrw.de/display/SEM/Kontakte)) gesammelten Personen. Wir ergänzen eine Spalte "eingeladen durch" zur Ergänzung der Person, die sich um die Einladung kümmert sowie "Handle" (auszufüllen, sobald sie registriert sind)
- [ ] Wir präsentieren das Forum am Montag, Leute können sich direkt registrieren und wir arbeiten 10 MInuten zusammen an der Erweiterung der Tabelle und legen bei Bedarf auch neue Arbeitsgruppen- oder Tool-Kategorien an. 

Ergibt das Sinn? Ansonsten gerne Punkte anpassen/ergänzen.

**Comment by Phu2** [comment]
Ich schließe das hier, weil wir Kategorien eingerichtet und Registrierung geöffnet haben. Präsentation bei KIM und vBIB ist auch geschehen.
