### ISSUE TITLE
Kacheln mit Logos und Kurzinfo in Tools-Kategorie

### ISSUE THREAD

**Issue by acka47** [hbz/metadaten.community#2]
Bei Socialhub wird m.E. gut eine Übersicht über Software geboten, indem Kacheln mit Logo und Kurzbeschreibung gezeigt werden: https://socialhub.activitypub.rocks/c/software/14

Das würde https://dev.metadaten.community/c/software-und-tools/5 auch gut stehen, wo momentan gar nicht die UNterkategorien auftauchen.

**Comment by Phu2** [comment]
Done, z. B. https://metadaten.community/c/software-und-tools/5

Die Anzeige der Unterkategorien kann man in den Einstellungen der jeweiligen Hauptkategorien anhaken und das Aussehen (Zeilen oder Boxen) festlegen. GGf. Logos für die KAtegorien hochladen.
