### ISSUE TITLE
Logo im Dark Mode fast nicht erkennbar

### ISSUE THREAD

**Issue by Phu2** [hbz/metadaten.community#3]
![grafik](https://github.com/hbz/metadaten.community/assets/726743/5b859fd2-5f37-48f3-a616-2a65f326d4eb)

**Comment by kaena83** [comment]
Habe das Logo angepasst.
![metadaten community_logo123](https://github.com/hbz/metadaten.community/assets/119848543/1d0f0c35-8918-4116-8066-fa6669a03c8f)

**Comment by kaena83** [comment]
Natürlich sind alle herzlich eingeladen andere Logos zu entwerfen (das ist auch kein Logo, eher ein Schrifttyp mit Rand...)

**Comment by kaena83** [comment]
Kontrast durch weißen Rand hergestellt, so dass auch in Dark Mode lesbar.
